Repository kubernetes/cluster-registry, pull requests merged in 2018-02, with the labels that each got.

#194 Add cluster-registry API reference docs
  docs/README.md
  docs/api-reference/clusterregistry/v1alpha1/definitions.html
  docs/api-reference/clusterregistry/v1alpha1/operations.html
  docs/api_reference.md
  hack/update-api-reference-docs.sh
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XXL

#192 Add aggregated and standalone delete sub-command with --force option
  pkg/crinit/aggregated/BUILD.bazel
  pkg/crinit/aggregated/aggregated.go
  pkg/crinit/aggregated/delete.go
  pkg/crinit/aggregated/doc.go
  pkg/crinit/aggregated/init.go
  pkg/crinit/common/BUILD.bazel
  pkg/crinit/common/common.go
  pkg/crinit/options/options.go
  pkg/crinit/standalone/BUILD.bazel
  pkg/crinit/standalone/delete.go
  pkg/crinit/standalone/doc.go
  pkg/crinit/standalone/init.go
  pkg/crinit/standalone/standalone.go
  pkg/crinit/util/util.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XXL

#193 Remove the internal version of the cluster API
  hack/update-codegen.sh
  pkg/apis/clusterregistry/BUILD.bazel
  pkg/apis/clusterregistry/doc.go
  pkg/apis/clusterregistry/install/BUILD.bazel
  pkg/apis/clusterregistry/install/install.go
  pkg/apis/clusterregistry/install/install_test.go
  pkg/apis/clusterregistry/register.go
  pkg/apis/clusterregistry/types.go
  pkg/apis/clusterregistry/v1alpha1/BUILD.bazel
  pkg/apis/clusterregistry/v1alpha1/validation/BUILD.bazel
  pkg/apis/clusterregistry/v1alpha1/validation/validation.go
  pkg/apis/clusterregistry/v1alpha1/validation/validation_test.go
  pkg/apis/clusterregistry/v1alpha1/zz_generated.conversion.go
  pkg/apis/clusterregistry/zz_generated.deepcopy.go
  pkg/apis/clusterregistry/zz_generated.defaults.go
  pkg/client/clientset_generated/internalclientset/BUILD.bazel
  pkg/client/clientset_generated/internalclientset/clientset.go
  pkg/client/clientset_generated/internalclientset/doc.go
  pkg/client/clientset_generated/internalclientset/fake/BUILD.bazel
  pkg/client/clientset_generated/internalclientset/fake/clientset_generated.go
  pkg/client/clientset_generated/internalclientset/fake/doc.go
  pkg/client/clientset_generated/internalclientset/fake/register.go
  pkg/client/clientset_generated/internalclientset/scheme/BUILD.bazel
  pkg/client/clientset_generated/internalclientset/scheme/doc.go
  pkg/client/clientset_generated/internalclientset/scheme/register.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/BUILD.bazel
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/cluster.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/clusterregistry_client.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/doc.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/fake/BUILD.bazel
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/fake/doc.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/fake/fake_cluster.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/fake/fake_clusterregistry_client.go
  pkg/client/clientset_generated/internalclientset/typed/clusterregistry/internalversion/generated_expansion.go
  pkg/client/informers_generated/internalversion/BUILD.bazel
  pkg/client/informers_generated/internalversion/clusterregistry/BUILD.bazel
  pkg/client/informers_generated/internalversion/clusterregistry/interface.go
  pkg/client/informers_generated/internalversion/clusterregistry/internalversion/BUILD.bazel
  pkg/client/informers_generated/internalversion/clusterregistry/internalversion/cluster.go
  pkg/client/informers_generated/internalversion/clusterregistry/internalversion/interface.go
  pkg/client/informers_generated/internalversion/factory.go
  pkg/client/informers_generated/internalversion/generic.go
  pkg/client/informers_generated/internalversion/internalinterfaces/BUILD.bazel
  pkg/client/informers_generated/internalversion/internalinterfaces/factory_interfaces.go
  pkg/client/listers_generated/clusterregistry/internalversion/BUILD.bazel
  pkg/client/listers_generated/clusterregistry/internalversion/cluster.go
  pkg/client/listers_generated/clusterregistry/internalversion/expansion_generated.go
  pkg/clusterregistry/BUILD.bazel
  pkg/clusterregistry/cluster.go
  pkg/clusterregistry/server.go
  pkg/registry/cluster/BUILD.bazel
  pkg/registry/cluster/etcd/BUILD.bazel
  pkg/registry/cluster/etcd/etcd.go
  pkg/registry/cluster/etcd/etcd_test.go
  pkg/registry/cluster/etcd/registrytestutil/BUILD.bazel
  pkg/registry/cluster/etcd/registrytestutil/registrytestutil.go
  pkg/registry/cluster/registry.go
  pkg/registry/cluster/strategy.go
  pkg/registry/cluster/strategy_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XXL

#201 Update Gopkg.toml to not have constraints.
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XL

#204 Fix clusterregistry.k8s.io:apiserver ClusterRole
  pkg/crinit/aggregated/aggregated.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#206 Update clientCIDR fields to match API definition
  examples/samplecontainer/cluster-two.yaml
  examples/samplecontainer/cluster.yaml
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#208 Typo: fix boostrap->bootstrap
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS
