Repository kubernetes/cluster-registry, pull requests merged in 2018-05, with the labels that each got.

#222 Update the OpenAPI spec for the v0.0.4 release.
  api/swagger.json
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#224 Highlight clone location.
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#228 Add namespaces to the cluster CRD
  cluster-registry-crd.yaml
  docs/reference/openapi-spec/swagger.json
  examples/cluster-two.yaml
  examples/cluster.yaml
  examples/slackcontroller/slackcontroller.go
  pkg/apis/clusterregistry/v1alpha1/types.go
  pkg/apis/clusterregistry/v1alpha1/zz_generated.kubebuilder.go
  pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/cluster.go
  pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/clusterregistry_client.go
  pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/fake/fake_cluster.go
  pkg/client/clientset/versioned/typed/clusterregistry/v1alpha1/fake/fake_clusterregistry_client.go
  pkg/client/informers/externalversions/clusterregistry/v1alpha1/cluster.go
  pkg/client/informers/externalversions/clusterregistry/v1alpha1/interface.go
  pkg/client/listers/clusterregistry/v1alpha1/cluster.go
  pkg/client/listers/clusterregistry/v1alpha1/expansion_generated.go
  test/integration/server_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/L

#232 Fix the user guide to work for namespaced clusters.
  docs/userguide.md
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#233 Add SECURITY_CONTACTS to the cluster registry repo
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/S

#235 Address follow up tasks from CRD conversion: LICENCES
  LICENSES
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XXL
