Repository kubernetes/cluster-registry, pull requests merged in 2018-04, with the labels that each got.

#218 Use k8s GCR vanity URL
  hack/update-api-reference-docs.sh
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#207 Remove cluster role and binding for clusters
  pkg/crinit/aggregated/aggregated.go
  pkg/crinit/aggregated/delete.go
  pkg/crinit/aggregated/init.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/L

#209 validates contents contained in createdRBACObj in aggregated test
  pkg/crinit/aggregated/aggregated_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/S
