Repository kubernetes/cluster-registry, pull requests merged in 2018-06, with the labels that each got.

#236 Some small updates to the cluster CRD YAML
  cluster-registry-crd.yaml
  docs/development.md
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/S

#237 Remove unnecessary code from pkg/inject, and clarify why that package and pkg/controller exist.
  pkg/controller/doc.go
  pkg/inject/args/args.go
  pkg/inject/doc.go
  pkg/inject/inject.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/M

#238 Update the cluster type definition to use a locally-defined object reference.
  cluster-registry-crd.yaml
  docs/reference/build/documents/_generated_authinfo_v1alpha1_clusterregistry_definition.md
  docs/reference/build/documents/_generated_objectreference_v1_core_definition.md
  docs/reference/build/documents/_generated_objectreference_v1alpha1_clusterregistry_definition.md
  docs/reference/build/index.html
  docs/reference/build/manifest.json
  docs/reference/build/navData.js
  docs/reference/openapi-spec/swagger.json
  pkg/apis/clusterregistry/v1alpha1/types.go
  pkg/apis/clusterregistry/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/clusterregistry/v1alpha1/zz_generated.kubebuilder.go
  test/integration/server_test.go
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/L

#239 s/cluster API/Cluster Registry API/g
  README.md
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#240 Remove the unused .bazelrc file.
  .bazelrc
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#246 Fix broken link to userguide
  examples/slackcontroller/README.md
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#245 Updated .gitignore.
  .gitignore
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS

#251 Updated promopt message for gofmt.
  hack/go-tools/verify-gofmt.sh
Labels: approved, cncf-cla: yes, lgtm, sig/multicluster, size/XS
