Repository kubernetes/cluster-registry, pull requests merged in 2019-03, with the labels that each got.

#268 Use a forked version of glog in kubernetes
  examples/slackcontroller/main.go
  examples/slackcontroller/slackcontroller.go
Labels: approved, cncf-cla: yes, lgtm, lifecycle/stale, needs-ok-to-test, sig/multicluster, size/M

#267 Fix typos: prefered->preferred, depedencies->dependencies
  docs/reference/build/README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, sig/multicluster, size/XS

#272 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS
